// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfVuxIOSP-EZxAdL5TCVJEQoQiB8qi8xI',
    appId: '1:980490342066:android:807dd912b296427d76c3ab',
    messagingSenderId: '980490342066',
    projectId: 'presence-bb101',
    storageBucket: 'presence-bb101.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD17vHvIBSn0js1TPKYCyTtEQ1HuxBdU-4',
    appId: '1:980490342066:ios:b84c799e79f0794a76c3ab',
    messagingSenderId: '980490342066',
    projectId: 'presence-bb101',
    storageBucket: 'presence-bb101.firebasestorage.app',
    iosBundleId: 'com.example.pressenceApp',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn7QUBjgaL6Qq9wTzmryXgcaNwCH_ptDY',
    appId: '1:980490342066:web:cf7339997485bab276c3ab',
    messagingSenderId: '980490342066',
    projectId: 'presence-bb101',
    authDomain: 'presence-bb101.firebaseapp.com',
    storageBucket: 'presence-bb101.firebasestorage.app',
    measurementId: 'G-7N16MQPE18',
  );
}
